# format="""$directory $git_branch$git_status$fill$cmd_duration$username$time\n$character
# """

format = """
$directory\
[󰣇 ](fg:#88C0D0)\
$git_branch\
$git_status\
$fill \
[ ](fg:#1d2230)\
\n$character
"""

right_format = """
$cmd_duration\
$username\
$time
"""

# コマンドラインに1行分のスペースを入れる
add_newline = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "user: [$user]($style) "
disabled = false


# left_promptとright_promptの間を何で埋めるか設定
[fill]
symbol = ' '

[directory]
style = "fg:#88C0D0"
# format = "[ $path ]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"
# truncation_symbol = ' ' # nf-fa-folder_open
# truncate_to_repo = false
# style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e bg:#0a0a0a'
format = '[ $path ]($style)[$read_only]($read_only_style)'


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
disabled = true
[gcloud]
disabled = true

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[git_branch]
symbol = ""
style = "fg:#1d2230"
format = '[[ $symbol $branch ](fg:#769ff0)]($style)'

[git_status]
style = "fg:#1d2230"
format = '[[($all_status$ahead_behind )](fg:#769ff0)]($style)'

[cmd_duration]
min_time = 1
style = 'fg:#f594ff'
format = "[ 󰑮 $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#a0a9cb"
format = '[[   $time ](fg:#94eeff)]($style)'

[character]
success_symbol = "[❯](bold fg:#88C0D0)" # Nordの明るい青
error_symbol = "[❯](bold fg:#BF616A)" # Nordの赤
vimcmd_symbol = '[V](bold green) '

